services:
  - type: web
    name: animal-crud
    runtime: php
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        scope: build
      - key: PORT
        value: "10000"
